call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_freight\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_freight" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5799\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5799" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP6039\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP6039" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5830\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5830" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5816\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5816" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP1648\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP1648" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP3010\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP3010" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5742\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5742" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP9018\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP9018" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP6064\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP6064" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5614\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5614" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5675\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5675" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP9005\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP9005" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KHP2_CP5871\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KHP2_CP5871" /S /I
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\Default\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\Default" /S /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\ACELA\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\ACELA\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\ACELA\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\ACELA\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\DASH9\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\DASH9\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\DASH9\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\DASH9\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\GP38\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\GP38\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\GP38\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\GP38\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\SCOTSMAN\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\SCOTSMAN\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\SCOTSMAN\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\SCOTSMAN\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KIHA31\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KIHA31\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\KIHA31\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\KIHA31\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\HHP\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\HHP\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\HHP\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\HHP\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\Series2000\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\Series2000\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\Series2000\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\Series2000\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\Series7000\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\Series7000\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\Series7000\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\Series7000\Sound" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\380\Cabview\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\380\Cabview" /I /C
call Xcopy "g:\Program Files\Microsoft Games\Train Simulator\Trains\Trainset\380\Sound\*.*" "f:\Mini_Routes\KHPass2\Train Simulator\Trains\Trainset\380\Sound" /I /C

